import { StyleSheet } from "react-native";

const vendordetailstyle = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#FFFFFF",
  },
  title: {
    fontSize: 24,
    fontFamily: "CalibriBold",
    color: "#000000",
    marginTop: 10,
    marginBottom: 20,
    marginLeft: 20,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 15,
    marginVertical: 5,
    shadowColor: "#000",
    padding: 15,
    elevation: 2,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
  },
  unavailableOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(128, 128, 128, 0.5)", // semi-transparent grey
    zIndex: 1,
    borderRadius: 10, // match your container radius if needed
  },
  quantityText: {
    fontFamily: "Calibri",
    fontSize: 16,
    verticalAlign: "middle",
    textAlign: "center",
  },
  counterbuttonText: {
    fontFamily: "Calibri",
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#000000",
    width: 40,
    fontSize: 30,
    height: 40,
    borderRadius: 360,
    alignContent: "center",
    verticalAlign: "middle",
    includeFontPadding: false,
    textAlign: "center",
  },
  counterContainer: {
    position: "absolute",
    bottom: 10,
    flexDirection: "row",
    width: "100%",
    alignSelf: "center",
    justifyContent: "space-between",
  },
  image: {
    width: 100,
    height: 100,
    borderRadius: 10,
    marginRight: 15,
  },
  info: {
    flex: 1,
  },
  BuyButtonContainer: {
    position: "absolute",
    bottom: 40,
    backgroundColor: "#ECA219",
    width: "95%",
    alignItems: "center",
    borderRadius: 50,
    marginHorizontal: 10,
    flexDirection: "row",
    paddingHorizontal: 20,
    zIndex: 1,
  },
  BuyButton: {
    flex: 1,
    borderRadius: 50,
    marginVertical: 10,
  },
  BuyButtonText1: {
    fontSize: 16,
    fontFamily: "CalibriBold",
    color: "white",
  },
  BuyButtonText2: {
    fontSize: 12,
    fontFamily: "CalibriBold",
    color: "white",
  },
  name: {
    fontSize: 18,
    fontFamily: "CalibriBold",
    color: "#000000",
  },
  description: {
    fontSize: 14,
    fontFamily: "Calibri",
    color: "#757575",
    marginTop: 5,
  },
  price: {
    fontSize: 16,
    fontFamily: "CalibriBold",
    marginTop: 10,
  },
  addButton: {
    backgroundColor: "#000000",
    width: "100",
    paddingVertical: 5,
    bottom: 0,
    right: 0,
    borderRadius: 20,
    alignItems: "center",
    position: "absolute",
  },
  smallercounterContainer: {
    width: "100",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  smallerquantityText: {
    fontFamily: "Calibri",
    fontSize: 16,
  },
  smallercounterbuttonText: {
    fontFamily: "Calibri",
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#000000",
    width: 30,
    fontSize: 20,
    height: 30,
    borderRadius: 360,
    alignContent: "center",
    verticalAlign: "middle",
    includeFontPadding: false,
    textAlign: "center",
  },
  addButtontoppicks: {
    backgroundColor: "#ffffff",
    width: "100%",
    borderColor: "#000000",
    borderWidth: 2,
    padding: 10,
    position: "absolute",
    bottom: 10,
    borderRadius: 20,
    alignItems: "center",
    alignSelf: "center",
    marginTop: 10,
  },
  availability: {
    fontSize: 14,
    fontFamily: "Calibri",
    color: "#4CAF50",
    marginTop: 5,
  },
  bought: {
    fontSize: 14,
    fontFamily: "Calibri",
    color: "#F44336",
    marginTop: 5,
  },
  bgimage: {
    width: "100%",
    height: 200,
    marginBottom: 110,
  },
  ppimg: {
    width: 100,
    height: 100,
    borderRadius: 10,
  },
  vendorname: {
    fontSize: 18,
    fontFamily: "CalibriBold",
    color: "#000000",
  },
  headercontainer: {
    position: "absolute",
    flexDirection: "row",
    top: 150,
    paddingHorizontal: 20,
    height: 150,
    width: "90%",
    elevation: 5,
    shadowColor: "#000",
    borderRadius: 20,
    backgroundColor: "#ffffff",
    alignItems: "center",
    alignSelf: "center",
  },
  header: {
    flexDirection: "column",
    marginLeft: 10,
  },
  TopPicksContainer: {
    width: 170,
    height: 290,
    marginRight: 10,
    marginBottom: 40,
  },
  FoodImg: {
    width: "100%",
    height: "100%",
    height: 150,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    elevation: 2,
  },
  FoodTextContainer: {
    backgroundColor: "white",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "50%",
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
  },
  FoodText: {
    color: "black",
    fontFamily: "CalibriBold",
    fontSize: 14,
  },
  FoodText2: {
    color: "black",
    fontSize: 10,
    fontFamily: "Calibri",
  },
});

export default vendordetailstyle;
